import fs from 'fs-extra';
import path from 'path';
import dedent from 'dedent';

import { resolveInCwd } from './cwd';
import { runBin } from './execute';

export const ensureConfigFile = async () => {
  const jestConfigPath = resolveInCwd('jest.config.js');
  const privateJestConfigPath = path.resolve(
    __dirname,
    '..',
    '..',
    'config',
    'jest',
    'index.js'
  );

  const configFileContents = dedent`
  /**
   * This file is managed automatically by pyaz.
   * Do not edit this file directly.
   */

  module.exports = require("${privateJestConfigPath}");
  `;
  await fs.writeFile(jestConfigPath, configFileContents);
};

export const runJest = async (args: readonly string[]) => {
  await ensureConfigFile();
  await runBin({
    packageName: 'jest',
    args,
    options: {
      stdio: 'inherit',
    },
  });
};
